#!/bin/bash
#adwpc
#it will update your packages !

OBJ=""
mv common "/tmp/common`date +%Y%m%d%H%M%S`" > /dev/null 2>&1
wget https://raw.githubusercontent.com/adwpc/common_sh/master/common
chmod u+x common
. common


function vim8_inst()
{
    if [[ "$OS_TYPE" =~ "CentOS" && "$OS_VER" == "7" ]];then
        centos7_vim_inst
    fi

    if [[ "$OS_TYPE" =~ "CentOS" && "$OS_VER" == "6" ]];then
        centos6_vim_inst
    fi

    if [[ "$OS_TYPE" == "Ubuntu" ]];then
        ubuntu_vim_inst
    fi

    if [[ "$OS_TYPE" == "Darwin" ]];then
        mac_vim_inst
    fi
}

function mac_vim_inst()
{
    brew install vim --with-cscope --with-python@2 --with-lua --override-system-vim
}

function centos7_vim_inst()
{
    cd /tmp
    wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/vim-common-8.0.003-1.gf.el7.x86_64.rpm
    wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/vim-minimal-8.0.003-1.gf.el7.x86_64.rpm
    wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/vim-enhanced-8.0.003-1.gf.el7.x86_64.rpm
    sudo yum install -y vim*.rpm
    rm vim*.rpm
    cd -
}

function centos6_vim_inst()
{
    #install deps
    sudo yum install -y git gcc gcc-c++ lua-devel ruby-devel perl-devel ncurses-devel make python-devel cmake perl-ExtUtils-Embed

    #install python2.7
    centos6_python2_inst

    #install new vim
    wget http://luajit.org/download/LuaJIT-2.0.4.tar.gz
    tar xzvf LuaJIT-2.0.4.tar.gz && cd LuaJIT-2.0.4 && make -j$CORES && sudo make install
    git clone https://github.com/vim/vim.git /tmp/vim
    cd /tmp/vim && ./configure --prefix=/usr/local/vim --enable-multibyte --enable-fontset --enable-xim --enable-gui=auto --enable-cscope --with-x --with-compiledby=adam --with-luajit --enable-luainterp=dynamic --enable-pythoninterp=yes --enable-pythoninterp=dynamic --enable-python3interp=dynamic --with-python-config-dir=/usr/local/python2.7/lib/python2.7/config --enable-rubyinterp=dynamic --enable-rubyinterp=yes --enable-perlinterp=yes
    make -j$CORES && sudo make install
    sudo mv /usr/bin/vim /usr/bin/vim.bak
    sudo ln -s /usr/local/vim/bin/vim /usr/bin/vim
    cd $CURDIR
}


function centos6_python2_inst()
{
    yum install -y gcc gcc-c++
    mkdir -p python2 && cd python2
    wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
    tar -xvf Python-2.7.12.tgz
    cd Python-2.7.12 && ./configure --prefix=/usr/local/python2.7 --with-threads --enable-shared
    make -j$CORES && sudo make install altinstall
    sudo ln -s /usr/local/python2.7/lib/libpython2.7.so /usr/lib
    sudo ln -s /usr/local/python2.7/lib/libpython2.7.so.1.0 /usr/lib
    sudo ln -s /usr/local/python2.7/bin/python2.7 /usr/local/bin
    sudo /sbin/ldconfig -v
    sudo mv /usr/bin/python /usr/bin/python.bak
    sudo ln -s /usr/local/bin/python2.7 /usr/bin/python
    sudo sed -i "s/python/python2.6/g" /usr/bin/yum

}


function ubuntu_vim_inst()
{
    #install deps
    sudo apt-get update
    sudo apt-get install -y git gcc g++ libluajit-5.1-dev ruby-dev libperl-dev ncurses-dev make python-dev cmake

    #install new vim
    rm -rf /tmp/vim
    git clone https://github.com/vim/vim.git /tmp/vim
    cd /tmp/vim && ./configure --prefix=/usr/local/vim --enable-multibyte --enable-fontset --enable-xim --enable-gui=auto --enable-cscope --with-x --with-compiledby=adam --with-luajit --enable-luainterp=dynamic --enable-pythoninterp=yes --enable-pythoninterp=dynamic --enable-python3interp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-rubyinterp=dynamic --enable-rubyinterp=yes --enable-perlinterp=yes
    make -j$CORES && sudo make install
    sudo mv /usr/bin/vim /usr/bin/vim.bak
    sudo ln -s /usr/local/vim/bin/vim /usr/bin/vim
    cd $CURDIR
}


function vimrc_inst()
{
    #install vim config and plugin
    mv ~/.vimrc ~/.vimrc.bak.`date +%Y%m%d%H%M%S`
    mv ~/.vim ~/.vim.bak.`date +%Y%m%d%H%M%S`
    cp -rf .vimrc ~
    cp -rf .vim ~
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim -u ~/.vimrc -c ":PlugInstall" -c ":q" -c ":q"
    
    #install ycm
    cd ~/.vim/plugged/YouCompleteMe/ ; git submodule update --init --recursive ; git submodule update --init --recursive ; ./install.py --all
    
}


if [ "$1" != ""  ];then
    OBJ=$1
fi
case "$OBJ" in
    vimrc) vimrc_inst;;
    vim8) vim8_inst;;

    *)  echo "Usage: install {vimrc|vim8}" >&2
        exit 1
        ;;
esac
