#!/bin/bash
#tested in ubuntu server 14.04.5 LTS
#it will update your packages !

OBJ=""
CURDIR=$PWD
INSTALLLOG=$CURDIR"/$0.log"
CORES=`cat /proc/cpuinfo | grep "processor" | wc -l`

function vim_inst()
{
    #install deps
    sudo apt-get update
    sudo apt-get install -y git gcc g++ libluajit-5.1-dev ruby-dev libperl-dev ncurses-dev make python-dev cmake

    #install new vim
    rm -rf /tmp/vim
    git clone https://github.com/vim/vim.git /tmp/vim
    cd /tmp/vim && ./configure --prefix=/usr/local/vim --enable-multibyte --enable-fontset --enable-xim --enable-gui=auto --enable-cscope --with-x --with-compiledby=adam --with-luajit --enable-luainterp=dynamic --enable-pythoninterp=yes --enable-pythoninterp=dynamic --enable-python3interp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-rubyinterp=dynamic --enable-rubyinterp=yes --enable-perlinterp=yes
    make -j$CORES && sudo make install
    sudo mv /usr/bin/vim /usr/bin/vim.bak
    sudo ln -s /usr/local/vim/bin/vim /usr/bin/vim
    cd $CURDIR
}

function vimrc_inst()
{
    #install vim config and plugin
    mv ~/.vimrc ~/.vimrc.bak
    mv ~/.vim ~/.vim.bak
    cp -rf .vim ~
    cp -rf .vimrc ~
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim -u ~/.vimrc -c ":PluginInstall" -c ":q" -c ":q"
    cd ~/.vim/bundle/YouCompleteMe/ && ./install.py --all
    vim -u ~/.vimrc -c ":GoInstallBinaries" -c ":q" /tmp/tmp.go
}

if [ "$1" != ""  ];then
    OBJ=$1
fi
case "$OBJ" in
    vim) vim_inst;;
    vimrc) vimrc_inst;;
    *)  echo "Usage: {vim|vimrc}" >&2
        echo "tested in ubuntu14.04" >&2
        exit 1
        ;;
esac
